import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-900 px-6 py-16">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="text-sm text-emerald-400 hover:text-emerald-300 transition-colors">
          &larr; Back to Home
        </Link>
        <h1 className="mt-8 text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-4 text-sm text-slate-400">Last updated: April 2026</p>

        <div className="mt-8 space-y-6 text-sm text-slate-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white">1. Acceptance of Terms</h2>
            <p className="mt-2">
              By accessing and using the AI Trading Debate Lab (&quot;the Platform&quot;), you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">2. Nature of the Service</h2>
            <p className="mt-2">
              The Platform provides an educational and entertainment service where AI-generated agents present opposing viewpoints on trade ideas. The content is generated by artificial intelligence and does not constitute financial advice, investment recommendations, or solicitations to buy or sell securities.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">3. No Financial Advice</h2>
            <p className="mt-2">
              Nothing on this Platform should be interpreted as financial advice. The debates are simulated arguments generated by AI for educational purposes. You should always conduct your own research and consult a qualified financial advisor before making investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">4. Limitation of Liability</h2>
            <p className="mt-2">
              The Platform is provided &quot;as is&quot; without warranties of any kind. We are not responsible for any financial decisions you make based on content viewed on this Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">5. Changes to Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. Continued use of the Platform constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">6. Contact</h2>
            <p className="mt-2">
              Questions about these Terms may be directed to our <Link href="/contact" className="text-emerald-400 hover:text-emerald-300 transition-colors">contact page</Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
