export function DisclaimerBanner() {
  return (
    <section
      className="bg-slate-950 px-6 py-8 min-h-[5vh]"
      aria-labelledby="disclaimer-heading"
      data-testid="disclaimer-banner"
    >
      <div className="mx-auto max-w-3xl">
        <details>
          <summary
            id="disclaimer-heading"
            className="cursor-pointer text-sm font-medium text-slate-300 min-h-[44px] flex items-center"
          >
            Trading involves risk. This is not financial advice.
          </summary>
          <div className="mt-4 space-y-3 text-sm text-slate-400">
            <p>
              The AI Trading Debate Lab is an educational and entertainment
              platform. The debates presented are generated by AI agents and
              should not be interpreted as financial advice, investment
              recommendations, or solicitations to buy or sell any securities.
            </p>
            <p>
              Past performance is not indicative of future results. All trading
              involves significant risk of loss. You should always conduct your
              own research and consult with a qualified financial advisor before
              making any investment decisions.
            </p>
            <p>
              The Bull and Bear arguments are AI-generated simulations and do
              not reflect the views of any real financial institution or
              advisor.
            </p>
          </div>
        </details>
      </div>
    </section>
  );
}
