import Link from "next/link";

export default function RiskDisclosurePage() {
  return (
    <div className="min-h-screen bg-slate-900 px-6 py-16">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="text-sm text-emerald-400 hover:text-emerald-300 transition-colors">
          &larr; Back to Home
        </Link>
        <h1 className="mt-8 text-3xl font-bold text-white">Risk Disclosure</h1>
        <p className="mt-4 text-sm text-slate-400">Last updated: April 2026</p>

        <div className="mt-8 space-y-6 text-sm text-slate-300 leading-relaxed">
          <section className="rounded-lg border border-rose-500/20 bg-rose-500/5 p-5">
            <p className="font-medium text-rose-300">
              This is not financial advice. All trading involves significant risk of loss.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">1. Nature of the Platform</h2>
            <p className="mt-2">
              The AI Trading Debate Lab is an educational and entertainment platform. The debates presented are generated by AI agents and should not be interpreted as financial advice, investment recommendations, or solicitations to buy or sell any securities or financial instruments.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">2. Trading Risks</h2>
            <p className="mt-2">
              All forms of trading carry substantial risk. The value of investments may go down as well as up, and you may not get back the amount originally invested. Past performance is not indicative of future results. You should be prepared to sustain a total loss of any capital you invest.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">3. AI-Generated Content</h2>
            <p className="mt-2">
              The Bull and Bear arguments are AI-generated simulations. They do not reflect the views of any real financial institution, advisor, or analyst. AI models can produce incorrect, incomplete, or biased outputs. Do not rely on AI-generated debate content for investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">4. No Guarantee of Results</h2>
            <p className="mt-2">
              The Platform makes no guarantees about the accuracy, completeness, or timeliness of the debate content. Debate outcomes and community votes are not predictive of market performance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">5. Independent Advice</h2>
            <p className="mt-2">
              You should always conduct your own independent research and consult with a qualified and licensed financial advisor before making any investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">6. Acknowledgment</h2>
            <p className="mt-2">
              By using this Platform, you acknowledge that you have read and understood this risk disclosure, and that you accept the risks associated with using an AI-generated educational tool in the context of financial markets.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
