export { truncateUnicode } from "./truncate";
export { captureSnapshot, slug } from "./snapshot";
export type { SnapshotOptions } from "./snapshot";
export { computePercentages } from "./percentages";
export type { PercentageBreakdown } from "./percentages";
export { trackEvent } from "./analytics";
export type { EventName, AnalyticsEvent } from "./analytics";
export { generateDebateStructuredData, deriveWinner } from "./structured-data";
export { getWinnerBadge } from "./winner-badge";
export type { WinnerBadge } from "./winner-badge";
export { formatRelativeTime } from "./format-time";
export { getOutcomeLabel } from "./filter-labels";
export { buildTweetIntentUrl, buildQuoteShareFilename, buildTweetText, validateTweetLength } from "./quote-share";
export { buildShareData, buildDebateShareUrl, isWebShareSupported } from "./share-debate";
